### ISSUE TITLE
How can I configure the elasticsearch instance with elasticsearch.yml

### ISSUE THREAD

**Issue by rszczypka** [cmourizard/sugar-docker-example#2]
I would like to change few things in the elasticsearch config

```
http.cors.enabled: true 
http.cors.allow-origin: "*" 
node.master: true
```

Can you please help me with making the change?

**Comment by cmourizard** [comment]
Sorry for this late answer, didn't see the notifications :-(

You can try to add a line "command" in the docker-compose file with by example command: elasticsearch -Des.node.master=true

**Comment by rszczypka** [comment]
Thanks @cmourizard ,
I wanted it to be able to use the elasticsearch plugins but in the end I was able to do it like that:

```
$ docker exec -it search bash
$ cd /usr/share/elasticsearch/bin
$/usr/share/elasticsearch/bin plugin install royrusso/elasticsearch-HQ/v1.0.0  
```
